### ISSUE TITLE
Does not support Japanese locale syntax

### ISSUE THREAD

**Issue by dricholm** [meyfa/line-chat-parser#1]
Current code will return empty array with exports from phone app that has locale set to Japanese. The date syntax is a bit different and the separator between time, author and message is a tab.

For example:
```
2018/04/16(月)
10:00	David	メッセージ
```

I forked the repo and added support for it. Is it okay to submit a pull request?

**Comment by meyfa** [comment]
Yes, absolutely. Thank you! That would be a good addition.

**Comment by meyfa** [comment]
I have just tested this from my (English locale) Android app, as well as from the Windows Store app on Windows 10. Both of them export the chat with a tab as the separator and with the date format you provided. Only the legacy Windows application uses the space formatting.

That means that by supporting tabs, we gain support for a whole new range of apps (and not specific to any locale). I think it also means the `users` array parameter can be optional (only used for the legacy formatting), as tabs unambiguously separate time, author, and message.

**Comment by dricholm** [comment]
Thank you for the quick response!

I see, `users` would not be needed then. I would be glad to help with it. I already created a fork when submitting the issue, which still has the `users` parameter and supports both. That could be rewritten, or leaving the old function alone and creating a new one which uses tabs for separation and does not need a users array?

How do you think it should be implemented?

**Comment by meyfa** [comment]
I made a commit that adds test cases for the syntax you provided, so we can test any implementation against that.

Leaving the `users` array alone for now (we can deal with that later), I think there are three things that need to be done:

1. Add another date matching block with a RegEx like the following: `/^(\d{4})\/(\d{1,2})\/(\d{1,2})\(.+\)/`
    This would give year in group 1, month in group 2, day in group 3. It could then be processed as usual.
2. Change the message matching RegEx to accept not just spaces, but spaces or tabs (or simply `\s` for any kind of whitespace).
3. Change the author detection so that it matches not just `user + " "`, but also `user + "\t"`.

Have I missed anything? Of course, these are just my ideas, there might be better ways, you are not bound to do it this way.

Feel free to submit any kind of PR, I'll happily merge it as long as it's useful.

**Comment by dricholm** [comment]
About the three things:
1. I changed the date matching RegEx to accept the previous syntax OR the new one: `^(\d{4})(?:\.|\/)(\d{2})(?:\.|\/)(\d{2})(?: [A-Z][a-z]+|\(.\))`
2. Similar to 1, message is accepted either with existing syntax OR a tab instead of space: `/^(\d{2}):(\d{2})(?: |\t)(\S.+)/`
3. About this, I removed the `prefix` variable and instead used only `user` there. It did work that way in tests and also with real chatlog. I wanted to ask why the extra space is needed after the user name.

I will submit the PR then. Please comment if you find something.
